feat(race,location): add moving members by races throw locations
shilovk/shipping pull request #1
Opened 2023-03-05 22:49 UTC by shilovk

2023-03-06 05:32 UTC, am-kantox requested changes
Взаимодействие между процессами — отлично, все, как надо (ну я бы еще интерфейс в `Location` определил).

Помарки я пометил, на будущее.

Но подразумевалось, все-таки, что этот код сможет решить подобную задачу для четырех других сущностей с иными сложностями взаимодействий (и найдет оба решения для этой задачи, а не одно из них).

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping/race.ex
> +  def handle_call({:start, start_loc, end_loc}, _from, passenger) do
```suggestion
  def handle_call({:start, start_loc, _end_loc}, _from, passenger) do
```

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping/race.ex
> +  def handle_call({:end, start_loc, end_loc}, _from, passenger) do
```suggestion
  def handle_call({:end, _start_loc, end_loc}, _from, passenger) do
```

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping.ex
> +    {:ok, pid} = Location.start_link(members, title)
Тут для `members` уместнее будет выглядеть [`MapSet`](https://hexdocs.pm/elixir/MapSet.html).

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping.ex
> +    members = ~w[wolf goat cabbage]a
Начинаем мы на берегу, полном атомов…

2023-03-06 05:32 UTC, am-kantox commented on test/shipping_test.exs
> +    assert ["wolf", "cabbage", "goat"] = Shipping.adventure
А где атомы? Почему тут строки?

Есть гипотеза, что вот такой тест провалится:

```elixir
    assert [] = GenServer.call({:via, Registry, "Location A"}, :members)
```

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping/location.ex
> +    members = members -- [passenger]
Тут неплохо бы проверить, что `passenger` есть в наличии среди `members`. 

```elixir
[:goat] -- [:wolf] #⇒ [:goat]
```

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping/race.ex
> +#  alias Shipping.Location
Мусор надо за собой убирать :)

2023-03-06 05:32 UTC, am-kantox commented on lib/shipping.ex
> +  end
Это не совсем то, что называется словом «решить» :)

А то я так умею много чего решать, вплоть до большой теоремы Ферма, когда ответ известен и надо рпосто подставить его в формулу.

2023-03-07 18:56 UTC, shilovk commented on test/shipping_test.exs
> +    assert ["wolf", "cabbage", "goat"] = Shipping.adventure
Да, вышла ошибка:

>   1) test check (ShippingTest)
>      test/shipping_test.exs:9
>      ** (FunctionClauseError) no function clause matching in Registry.whereis_name/1
> 
>      The following arguments were given to Registry.whereis_name/1:
>      
>          # 1
>          "Location A"
>      
>      Attempted function clauses (showing 2 out of 2):
>      
>          def whereis_name({registry, key})
>          def whereis_name({registry, key, _value})
>      
>      code: assert [] = GenServer.call({:via, Registry, "Location A"}, :members)
>      stacktrace:
>        (elixir 1.14.3) lib/registry.ex:223: Registry.whereis_name/1
>        (elixir 1.14.3) lib/gen_server.ex:1214: GenServer.whereis/1
>        (elixir 1.14.3) lib/gen_server.ex:1025: GenServer.call/3
>        test/shipping_test.exs:10: (test)
> 
> .
> Finished in 0.06 seconds (0.00s async, 0.06s sync)
> 2 tests, 1 failure

2023-03-07 18:59 UTC, shilovk commented on lib/shipping/location.ex
> +    members = members -- [passenger]
@am-kantox  Сделал `MapSet.delete(members, passenger)` и такой ошибки не будет. Если все же нужно проверять, то исключение вызывать как то?

2023-03-07 19:08 UTC, shilovk commented
> бы еще интерфейс в `Location` определил

@am-kantox Как сделать такое определение, интерфейс интересное что такое?

2023-03-08 04:44 UTC, am-kantox commented on lib/shipping/location.ex
> +    {:reply, :remove, MapSet.delete(members, passenger)}
Вопрос не в мапсете же. Надо проверять в данном случае, что мы можем удалять, то есть два разных случая:

```elixir
  def handle_call({:remove, passenger}, _from, members) when passenger in members do
    ...
  end
  def handle_call({:remove, passenger}, _from, members), do: {:reply, :error, members}
```

2023-03-08 09:44 UTC, shilovk commented on lib/shipping/location.ex
> +    {:reply, :remove, MapSet.delete(members, passenger)}
`def handle_call({:remove, passenger}, _from, members) when passenger in members do`

Вышла ошибка, интересно почему? 

>>** (ArgumentError) invalid right argument for operator "in", it expects a compile-time proper list or compile-time range on the right side when used in guard expressions, got: members
(elixir 1.14.3) lib/kernel.ex:4342: Kernel.raise_on_invalid_args_in_2/1
(elixir 1.14.3) expanding macro: Kernel.in/2

2023-03-08 09:48 UTC, am-kantox commented on lib/shipping/location.ex
> +    {:reply, :remove, MapSet.delete(members, passenger)}
> `def handle_call({:remove, passenger}, _from, members) when passenger in members do`
> 
> Вышла ошибка, интересно почему?

Потому что это гард, разные клаузы функций генерируются на стадии компиляции и поэтому «it expects a compile-time proper list or compile-time range on the right side when used in guard expressions, got: members».

Компилятор напрямую же пишет, так что придется в одном клаузе через `case/2`.

2023-03-08 09:56 UTC, shilovk commented on lib/shipping/location.ex
> +    {:reply, :remove, MapSet.delete(members, passenger)}
Новый интересный момент, как выполнить, если не разрешает?

```
  @impl GenServer
  def handle_call({:remove, passenger}, _from, members) do
    case passenger in members do
      {:reply, :remove, MapSet.delete(members, passenger)} -> true
      {:reply, :error, members} -> false
    end
  end
```

> == Compilation error in file lib/shipping/location.ex ==
> ** (CompileError) lib/shipping/location.ex:22: cannot invoke remote function MapSet.delete/2 inside a match
>     (stdlib 4.2) lists.erl:1462: :lists.mapfoldl_1/3

2023-03-08 10:17 UTC, am-kantox commented on lib/shipping/location.ex
> +    {:reply, :remove, MapSet.delete(members, passenger)}
Если вы еще раз посмотрите на код, вы сообразите сами, что тут не так.

2023-03-08 15:06 UTC, merged